# Generated by Django 4.2.6 on 2023-11-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='title',
            field=models.CharField(default='teacher', max_length=30),
            preserve_default=False,
        ),
    ]
